import Navigation from "@/Components/Navigation";
import './globals.css'

export const metadata = {
  title: 'My First Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/lux/bootstrap.min.css" />
      </head>
      <body>
        <Navigation/>
        <div className="container p-4">
        {children}
        </div>
        </body>
    </html>
  )
}
